[package]
name          = "starknet_ibc_testing"
version       = { workspace = true }
edition       = { workspace = true }
cairo-version = { workspace = true }
scarb-version = { workspace = true }
authors       = { workspace = true }
repository    = { workspace = true }
license       = { workspace = true }
Readme        = { workspace = true }
keywords      = { workspace = true }
description   = { workspace = true }

[dependencies]
# external dependencies
starknet             = { workspace = true }
openzeppelin_token   = { workspace = true }
openzeppelin_testing = { workspace = true }
openzeppelin_utils   = { workspace = true }

# ibc dependencies
starknet_ibc_utils        = { workspace = true }
starknet_ibc_core_client  = { workspace = true }
starknet_ibc_app_transfer = { workspace = true }
starknet_ibc_presets      = { workspace = true }

[dev-dependencies]
cairo_test  = { workspace = true }
snforge_std = { workspace = true }

[lib]

[tool]
fmt = { workspace = true }

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
sierra                     = true
casm                       = false
