[package]
name          = "starknet_ibc"
version       = "0.1.0"
license       = "Apache-2.0"
edition       = "2023_11"
cairo-version = "2.6.4"
scarb-version = "2.6.5"
repository    = "https://github.com/informalsystems/ibc-starknet"
authors       = ["Informal Systems <hello@informal.systems>"]
Readme        = "README.md"
keywords      = ["ethereum", "starknet", "cairo", "ibc", "ibc-rs"]
description   = "Collection of Cairo components and contracts that implement and integrate IBC protocol with Starknet"

[dependencies]
starknet      = ">=2.6.0"
openzeppelin  = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.14.0" }
snforge_std   = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.25.0" }

[lib]

[[target.starknet-contract]]

[tool.fmt]
sort-module-level-items = true