[package]
name         = "hermes-starknet-chain-components"
version      = { workspace = true }
edition      = { workspace = true }
license      = { workspace = true }
keywords     = { workspace = true }
repository   = { workspace = true }
authors      = { workspace = true }
rust-version = { workspace = true }
readme       = "README.md"

[dependencies]
cgp                                 = { workspace = true }
hermes-relayer-components           = { workspace = true }
hermes-test-components              = { workspace = true }
hermes-encoding-components          = { workspace = true }
hermes-cosmos-chain-components      = { workspace = true }
hermes-wasm-client-components       = { workspace = true }
hermes-cairo-encoding-components    = { workspace = true }
hermes-protobuf-encoding-components = { workspace = true }

ibc                                 = { workspace = true }
ibc-proto                           = { workspace = true }
ibc-relayer-types                   = { workspace = true }

starknet                    = { workspace = true }
serde_json                  = { workspace = true }
cairo-lang-starknet-classes = { workspace = true }
ibc-client-starknet-types   = { workspace = true }
prost-types                 = { workspace = true }
